when:
  branch: master

steps:
  build:
    image: alpine
    when:
      event: push
    commands:
      - wget -O minify.tar.gz https://github.com/tdewolff/minify/releases/download/v2.24.14/minify_linux_amd64.tar.gz
      - wget -O zine.tar.xz https://github.com/kristoff-it/zine/releases/download/v0.13.0/x86_64-linux-musl.tar.xz
      - tar xf zine.tar.xz
      - tar xf minify.tar.gz minify
      - ./zine release -o .ci/build
      - ./minify -ari .ci/build

  publish:
    image: alpine/git
    depends_on: build
    when:
      event: [push]
    environment:
      FORGEJO_TOKEN:
        from_secret: "forgejo_token"
    commands:
      - git config --global user.email "noreply+woodpecker@ririna.net"
      - git config --global user.name "john woodpecker"

      - git clone --branch pages --depth 1 "https://$${FORGEJO_TOKEN}@repo.ririna.net/dragsbruh/pages.git" .ci/publish
      - cd .ci/publish

      - git rm -r . || true
      - cp -a ../build/. .

      - git add --all
      - git commit -m "ci (trigger by ${CI_COMMIT_SHA})" --allow-empty
      - git push
