when:
  branch: main

steps:
  build:
    image: alpine
    when:
      event: push
    commands:
      - wget -O minify.tar.gz https://github.com/tdewolff/minify/releases/download/v2.24.13/minify_linux_amd64.tar.gz
      - wget -O zine.tar.xz https://github.com/kristoff-it/zine/releases/download/v0.12.0/x86_64-linux-musl.tar.xz
      - tar xf zine.tar.xz
      - tar xf minify.tar.gz minify
      - ./zine release -o .build/
      - ./minify -ari .build/

  publish:
    image: alpine/git
    depends_on: build
    when:
      event: [push]
    environment:
      CODEBERG_TOKEN:
        from_secret: "codeberg_token"
    commands:
      - git config --global user.email "ci@furina.is-a.dev"
      - git config --global user.name "Woodpecker CI"

      - git clone --branch pages --depth 1 https://$${CODEBERG_TOKEN}@codeberg.org/$CI_REPO.git .publish
      - cd .publish

      - git rm -r . || true
      - cp -a ../.build/. .

      - git add --all
      - git commit -m "Woodpecker CI ${CI_COMMIT_SHA}" --allow-empty
      - git push
